assistant:
  language: en
  wakewords:
  - bumblebee
  - americano
  allow_only_known_speakers: true
  user_initialized: true
  volume: 0.8
  silenced_volume: 0.1
  show_balloon: true
defaults:
  de:
    no_intent_recognized:
    - Ich habe dich nicht verstanden
    - Den Befehl habe ich nicht verstanden
