intent:
  volume:
    de:
      invalid_volume: ["Bitte nenne eine Lautstärke zwischen 0 und 10"]
      volume_up: "lauter"
      volume_down: "leiser"
      volume_is: "Die Lautstärke ist {} von zehn."
      set_volume: "Die Lautstärke wurde auf {} gesetzt."
    en:
      invalid_volume: ["Please set the volume between 0 and 10"]
      volume_up: "louder"
      volume_down: "quieter"
      volume_is: "Volume is {} out of ten."
      set_volume: "The volume has been set to {}."
    fr:
      invalid_volume: [ "Veuillez définir un volume entre 0 et 10." ]
      volume_up: "plus fort"
      volume_down: "moins fort"
      volume_is: "Le volume est de {} sur dix."
      set_volume: "Le volume a été réglé à {}."
    es:
      invalid_volume: [ "Por favor, ajusta el volumen entre 0 y 10." ]
      volume_up: "más alto"
      volume_down: "más bajo"
      volume_is: "El volumen es {} de diez."
      set_volume: "El volumen se ha ajustado a {}."
    it:
      invalid_volume: [ "Per favore, imposta un volume tra 0 e 10." ]
      volume_up: "più alto"
      volume_down: "più basso"
      volume_is: "Il volume è {} su dieci."
      set_volume: "Il volume è stato impostato a {}."
    ja:
      invalid_volume: [ "音量を0から10の間で設定してください。" ]
      volume_up: "もっと大きく"
      volume_down: "もっと小さく"
      volume_is: "音量は10のうち{}です。"
      set_volume: "音量が{}に設定されました。"
    ru:
      invalid_volume: [ "Пожалуйста, установите громкость от 0 до 10." ]
      volume_up: "громче"
      volume_down: "тише"
      volume_is: "Громкость составляет {} из десяти."
      set_volume: "Громкость установлена на {}."