intent:
  reminder:
    de:
      reminder_same_day_infinitive: ["Ich werde dich um {} Uhr {} daran erinnern {} ."]
      reminder_infinitive: ["Ich erinnere dich am {} {} {} um {} Uhr {} daran {} ."]
      reminder_same_day_to: ["Ich erinnere dich um {} Uhr {} {} ."]
      reminder_to: ["Ich erinnere dich am {} {} {} um {} Uhr {} {} ."]
      reminder_same_day_no_action: ["Ich erinnere dich um {} Uhr {} ."]
      reminder_no_action: ["Ich erinnere dich am {} {} {} um {} Uhr {} ."]
      no_time_given: ["Ich habe leider das Erinnerungsdatum beziehungsweise die Uhrzeit nicht verstanden."]
      invalid_time_given: ["Gebe eine gültige Uhrzeit an."]

      execute_reminder_infinitive: ["Ich soll dich daran erinnern {} ."]
      execute_reminder_to: ["Ich erinnere dich {} ."]
      execute_reminder: ["Ich soll dich jetzt erinnern.", "Das ist die gewünschte Erinnerung."]
    en:
      reminder_same_day_infinitive: [ "I'll remind you at {} {} to {} ." ]
      reminder_infinitive: [ "I'll remind you on the {} at {} {} to {} ." ]
      reminder_same_day_to: [ "I'll remind you at {} {} to {} ." ]
      reminder_to: [ "I'll remind you on the {} at {} {} to {} ." ]
      reminder_same_day_no_action: [ "I'll remind you at {} {} ." ]
      reminder_no_action: [ "I'll remind you on the {} at {} {} ." ]
      no_time_given: [ "I could not understand the time to remind you." ]
      invalid_time_given: [ "Please provide a valid time." ]

      execute_reminder_infinitive: [ "I want to remind you to {} ." ]
      execute_reminder_to: [ "I want to remind you to {} ." ]
      execute_reminder: [ "This is a reminder.", "Here is your requested reminder." ]
    es:
      reminder_same_day_infinitive: [ "Te recordaré a las {} {} que {} ." ]
      reminder_infinitive: [ "Te recordaré el {} a las {} {} que {} ." ]
      reminder_same_day_to: [ "Te recordaré a las {} {} de {} ." ]
      reminder_to: [ "Te recordaré el {} a las {} {} de {} ." ]
      reminder_same_day_no_action: [ "Te recordaré a las {} {} ." ]
      reminder_no_action: [ "Te recordaré el {} a las {} {} ." ]
      no_time_given: [ "No pude entender la hora para recordarte." ]
      invalid_time_given: [ "Por favor, proporciona una hora válida." ]

      execute_reminder_infinitive: [ "Quiero recordarte que {} ." ]
      execute_reminder_to: [ "Quiero recordarte de {} ." ]
      execute_reminder: [ "Este es un recordatorio.", "Aquí tienes tu recordatorio solicitado." ]
    fr:
      reminder_same_day_infinitive: [ "Je te rappellerai à {} {} de {} ." ]
      reminder_infinitive: [ "Je te rappellerai le {} à {} {} de {} ." ]
      reminder_same_day_to: [ "Je te rappellerai à {} {} de {} ." ]
      reminder_to: [ "Je te rappellerai le {} à {} {} de {} ." ]
      reminder_same_day_no_action: [ "Je te rappellerai à {} {} ." ]
      reminder_no_action: [ "Je te rappellerai le {} à {} {} ." ]
      no_time_given: [ "Je n'ai pas compris l'heure pour te rappeler." ]
      invalid_time_given: [ "Veuillez fournir une heure valide." ]

      execute_reminder_infinitive: [ "Je veux te rappeler de {} ." ]
      execute_reminder_to: [ "Je veux te rappeler de {} ." ]
      execute_reminder: [ "Voici un rappel.", "Voici le rappel demandé." ]
    it:
      reminder_same_day_infinitive: [ "Ti ricorderò alle {} {} di {} ." ]
      reminder_infinitive: [ "Ti ricorderò il {} alle {} {} di {} ." ]
      reminder_same_day_to: [ "Ti ricorderò alle {} {} di {} ." ]
      reminder_to: [ "Ti ricorderò il {} alle {} {} di {} ." ]
      reminder_same_day_no_action: [ "Ti ricorderò alle {} {} ." ]
      reminder_no_action: [ "Ti ricorderò il {} alle {} {} ." ]
      no_time_given: [ "Non ho capito l'ora per ricordarti." ]
      invalid_time_given: [ "Per favore, fornisci un orario valido." ]

      execute_reminder_infinitive: [ "Voglio ricordarti di {} ." ]
      execute_reminder_to: [ "Voglio ricordarti di {} ." ]
      execute_reminder: [ "Questo è un promemoria.", "Ecco il tuo promemoria richiesto." ]
    ja:
      reminder_same_day_infinitive: [ "{}時{}分に{}を思い出させます。" ]
      reminder_infinitive: [ "{}年{}月{}日、{}時{}分に{}を思い出させます。" ]
      reminder_same_day_to: [ "{}時{}分に{}を思い出させます。" ]
      reminder_to: [ "{}年{}月{}日、{}時{}分に{}を思い出させます。" ]
      reminder_same_day_no_action: [ "{}時{}分に思い出させます。" ]
      reminder_no_action: [ "{}年{}月{}日、{}時{}分に思い出させます。" ]
      no_time_given: [ "リマインドする時間が理解できませんでした。" ]
      invalid_time_given: [ "有効な時間を指定してください。" ]

      execute_reminder_infinitive: [ "{}を思い出させます。" ]
      execute_reminder_to: [ "{}を思い出させます。" ]
      execute_reminder: [ "これがリマインダーです。", "リクエストされたリマインダーです。" ]
    ru:
      reminder_same_day_infinitive: [ "Я напомню вам в {} {} о {} ." ]
      reminder_infinitive: [ "Я напомню вам {} в {} {} о {} ." ]
      reminder_same_day_to: [ "Я напомню вам в {} {} о {} ." ]
      reminder_to: [ "Я напомню вам {} в {} {} о {} ." ]
      reminder_same_day_no_action: [ "Я напомню вам в {} {} ." ]
      reminder_no_action: [ "Я напомню вам {} в {} {} ." ]
      no_time_given: [ "Я не смог понять время, чтобы напомнить вам." ]
      invalid_time_given: [ "Пожалуйста, укажите корректное время." ]

      execute_reminder_infinitive: [ "Я хочу напомнить вам о {} ." ]
      execute_reminder_to: [ "Я хочу напомнить вам о {} ." ]
      execute_reminder: [ "Это ваше напоминание.", "Вот ваше запрошенное напоминание." ]

  timer:
    de:
      timer_hour: [ "Ich setze einen Timer auf {} Stunden ." ]
      timer_minute: [ "Ich setze einen Timer auf {} Minuten ." ]
      timer_second: [ "Ich setze einen Timer auf {} Sekunden ." ]
      named_timer_hour: [ "Ich setze den Timer {} auf {} Stunden ." ]
      named_timer_minute: [ "Ich setze den Timer {} auf {} Minuten ." ]
      named_timer_second: [ "Ich setze den Timer {} auf {} Sekunden ." ]
      no_timer_given: [ "Ich habe leider deinen Timer nicht verstanden." ]

      execute_timer: [ "Dein Timer ist abgelaufen." ]
      execute_named_timer: [ "Dein Timer {} ist abgelaufen." ]
    en:
      timer_hour: [ "I'm setting a timer for {} hours." ]
      timer_minute: [ "I'm setting a timer for {} minutes." ]
      timer_second: [ "I'm setting a timer for {} seconds." ]
      named_timer_hour: [ "I'm setting the timer {} for {} hours." ]
      named_timer_minute: [ "I'm setting the timer {} for {} minutes." ]
      named_timer_second: [ "I'm setting the timer {} for {} seconds." ]
      no_timer_given: [ "I couldn't understand your timer request." ]

      execute_timer: [ "Your timer has finished." ]
      execute_named_timer: [ "Your timer {} has finished." ]
    es:
      timer_hour: [ "Voy a configurar un temporizador para {} horas." ]
      timer_minute: [ "Voy a configurar un temporizador para {} minutos." ]
      timer_second: [ "Voy a configurar un temporizador para {} segundos." ]
      named_timer_hour: [ "Voy a configurar el temporizador {} para {} horas." ]
      named_timer_minute: [ "Voy a configurar el temporizador {} para {} minutos." ]
      named_timer_second: [ "Voy a configurar el temporizador {} para {} segundos." ]
      no_timer_given: [ "No entendí tu solicitud de temporizador." ]

      execute_timer: [ "Tu temporizador ha finalizado." ]
      execute_named_timer: [ "Tu temporizador {} ha finalizado." ]
    fr:
      timer_hour: [ "Je règle un minuteur pour {} heures." ]
      timer_minute: [ "Je règle un minuteur pour {} minutes." ]
      timer_second: [ "Je règle un minuteur pour {} secondes." ]
      named_timer_hour: [ "Je règle le minuteur {} pour {} heures." ]
      named_timer_minute: [ "Je règle le minuteur {} pour {} minutes." ]
      named_timer_second: [ "Je règle le minuteur {} pour {} secondes." ]
      no_timer_given: [ "Je n'ai pas compris ta demande de minuteur." ]

      execute_timer: [ "Ton minuteur est terminé." ]
      execute_named_timer: [ "Ton minuteur {} est terminé." ]
    it:
      timer_hour: [ "Imposto un timer per {} ore." ]
      timer_minute: [ "Imposto un timer per {} minuti." ]
      timer_second: [ "Imposto un timer per {} secondi." ]
      named_timer_hour: [ "Imposto il timer {} per {} ore." ]
      named_timer_minute: [ "Imposto il timer {} per {} minuti." ]
      named_timer_second: [ "Imposto il timer {} per {} secondi." ]
      no_timer_given: [ "Non ho capito la tua richiesta di timer." ]

      execute_timer: [ "Il tuo timer è scaduto." ]
      execute_named_timer: [ "Il tuo timer {} è scaduto." ]
    ja:
      timer_hour: [ "{}時間のタイマーを設定します。" ]
      timer_minute: [ "{}分のタイマーを設定します。" ]
      timer_second: [ "{}秒のタイマーを設定します。" ]
      named_timer_hour: [ "{}のタイマーを{}時間に設定します。" ]
      named_timer_minute: [ "{}のタイマーを{}分に設定します。" ]
      named_timer_second: [ "{}のタイマーを{}秒に設定します。" ]
      no_timer_given: [ "タイマーリクエストが理解できませんでした。" ]

      execute_timer: [ "タイマーが終了しました。" ]
      execute_named_timer: [ "{}のタイマーが終了しました。" ]
    ru:
      timer_hour: [ "Я устанавливаю таймер на {} часов." ]
      timer_minute: [ "Я устанавливаю таймер на {} минут." ]
      timer_second: [ "Я устанавливаю таймер на {} секунд." ]
      named_timer_hour: [ "Я устанавливаю таймер {} на {} часов." ]
      named_timer_minute: [ "Я устанавливаю таймер {} на {} минут." ]
      named_timer_second: [ "Я устанавливаю таймер {} на {} секунд." ]
      no_timer_given: [ "Я не понял ваш запрос на таймер." ]

      execute_timer: [ "Ваш таймер завершен." ]
      execute_named_timer: [ "Ваш таймер {} завершен." ]