intent:
  musicstream:
    de:
      unknown_station: ["Den Radiosender kenne ich nicht."]
    en:
      unknown_station: ["I don't know that station."]
    stations:
      "deutschlandfunk": "https://st01.sslstream.dlf.de/dlf/01/128/mp3/stream.mp3"
      "hr 1": "https://dispatcher.rndfnk.com/hr/hr1/live/mp3/high"
      "mdr aktuell": "https://avw.mdr.de/streams/284340-0_mp3_high.m3u"
      "ndr 2": "https://www.ndr.de/resources/metadaten/audio/m3u/ndr2.m3u"
      "mdr jump": "https://avw.mdr.de/streams/284320-0_mp3_high.m3u"
      "sonnenschein live": "https://sunsl.streamabc.net/sunsl-sunslhardstyle-mp3-192-5865645"