intent:
  wiki:
    de:
      unknown_entity: ["Ich weiß nichts über {}.", "{} sagt mir nichts."]
      answer: ["{}\n\nMöchtest du mehr erfahren?"]
      more_answer: ["{}"]
      no_session: ["Die Sitzung existiert nicht. Bitte starten Sie den Vorgang erneut."]
      unclear_input: ["Ich habe dich nicht verstanden."]
      standard: ["Alles klar. Was kann ich noch für dich tun?"]
      alternativ: ["Deine Anfrage ist mehrdeutig. Meintest du eine der folgenden Optionen? {}"]
      yes_answers: ["ja", "natürlich", "klar", "gerne", "bitte"]
      no_answers: ["nein", "nicht", "abbrechen"]
    en:
      unknown_entity: ["I don't know {}.", "{} rings no bell."]
      answer: ["{}\n\nWould you like to know more?"]
      more_answer: ["{}"]
      no_session: ["The session does not exist. Please start the process again."]
      unclear_input: ["I didn't catch that. Would you like to know more?"]
      standard: ["Alright. What else can I do for you?"]
      alternativ: ["Your query is ambiguous. Did you mean one of the following options? {}"]
      yes_answers: ["yes", "sure", "of course", "please", "go ahead"]
      no_answers: ["no", "cancel", "abort"]
    fr:
      unknown_entity: ["Je ne sais rien sur {}.", "{} ne me dit rien."]
      answer: ["{}\n\nVoulez-vous en savoir plus?"]
      more_answer: ["Voici plus d'informations: {}"]
      no_session: ["La session n'existe pas. Veuillez recommencer le processus."]
      unclear_input: ["Je ne vous ai pas compris. Voulez-vous en savoir plus?"]
      standard: ["D'accord. Que puis-je faire d'autre pour vous?"]
      alternativ: ["Votre requête est ambiguë. Voulez-vous dire une des options suivantes? {}"]
      yes_answers: ["oui", "bien sûr", "certainement", "s'il vous plaît"]
      no_answers: ["non", "annuler", "abandonner"]
    es:
      unknown_entity: ["No sé nada sobre {}.", "{} no me suena de nada."]
      answer: ["{}\n\n¿Te gustaría saber más?"]
      more_answer: ["Aquí tienes más información: {}"]
      no_session: ["La sesión no existe. Por favor, comienza el proceso de nuevo."]
      unclear_input: ["No entendí eso. ¿Te gustaría saber más?"]
      standard: ["De acuerdo. ¿Qué más puedo hacer por ti?"]
      alternativ: ["Tu consulta es ambigua. ¿Te referías a una de las siguientes opciones? {}"]
      yes_answers: ["sí", "claro", "por supuesto", "adelante"]
      no_answers: ["no", "cancelar", "abortar"]
    it:
      unknown_entity: ["Non so nulla su {}.", "{} non mi dice nulla."]
      answer: ["{}\n\nVuoi sapere di più?"]
      more_answer: ["Ecco altre informazioni: {}"]
      no_session: ["La sessione non esiste. Per favore, ricomincia il processo."]
      unclear_input: ["Non ho capito. Vuoi sapere di più?"]
      standard: ["Va bene. Cos'altro posso fare per te?"]
      alternativ: ["La tua richiesta è ambigua. Intendevi una delle seguenti opzioni? {}"]
      yes_answers: ["sì", "certo", "ovviamente", "prego"]
      no_answers: ["no", "annullare", "abortire"]
    ja:
      unknown_entity: ["{}については何も知りません。", "{}は聞いたことがありません。"]
      answer: ["{}\n\nもっと知りたいですか？"]
      more_answer: ["こちらはさらに詳しい情報です: {}"]
      no_session: ["セッションは存在しません。もう一度やり直してください。"]
      unclear_input: ["聞き取れませんでした。もっと知りたいですか？"]
      standard: ["わかりました。他に何をお手伝いしましょうか？"]
      alternativ: ["リクエストが曖昧です。次のオプションのどれかを指していましたか？ {}"]
      yes_answers: ["はい", "もちろん", "お願いします", "どうぞ"]
      no_answers: ["いいえ", "キャンセル", "中止"]
    ru:
      unknown_entity: ["Я ничего не знаю о {}.", "{} мне ни о чём не говорит."]
      answer: ["{}\n\nХотите узнать больше?"]
      more_answer: ["Вот дополнительная информация: {}"]
      no_session: ["Сессии не существует. Пожалуйста, начните процесс заново."]
      unclear_input: ["Я вас не понял. Хотите узнать больше?"]
      standard: ["Хорошо. Чем ещё могу помочь?"]
      alternativ: ["Ваш запрос неоднозначен. Вы имели в виду одну из следующих опций? {}"]
      yes_answers: ["да", "конечно", "пожалуйста", "разумеется"]
      no_answers: ["нет", "отмена", "прекратить"]
