intent:
  password:
    de:
      unknown_entry: [ "Ich habe keine Zugangsdaten für {} gefunden." ]
      typed_pw: "Passwort für {} getippt"
      db_not_found: "Die Passwortdatenbank wurde nicht gefunden."
      key_not_found: "Der Schlüssel für die Datenbank wurde nicht gefunden."
      could_not_access_keystore: "Konnte Passwortdatenbank nicht öffnen."
      no_voice_match: "Du darfst leider nicht auf die Passwortdatenbank zugreifen."
    en:
      unknown_entity: [ "I could not find any credentials for {}." ]
      typed_pw: "Typed password for {}"
      db_not_found: "The key database was not found."
      key_not_found: "The secret key to access the database was not found."
      could_not_access_keystore: "Could not open keystore"
      no_voice_match: "You are not allowed to access the keystore"
    fr:
      unknown_entry: [ "Je n'ai trouvé aucune donnée d'accès pour {}." ]
      typed_pw: "Mot de passe tapé pour {}"
      db_not_found: "La base de données des mots de passe n'a pas été trouvée."
      key_not_found: "La clé secrète pour accéder à la base de données n'a pas été trouvée."
      could_not_access_keystore: "Impossible d'ouvrir la base de données des mots de passe."
      no_voice_match: "Vous n'êtes pas autorisé à accéder à la base de données des mots de passe."
    es:
      unknown_entry: [ "No encontré ninguna credencial para {}." ]
      typed_pw: "Contraseña escrita para {}"
      db_not_found: "No se encontró la base de datos de contraseñas."
      key_not_found: "No se encontró la clave para acceder a la base de datos."
      could_not_access_keystore: "No se pudo abrir la base de datos de contraseñas."
      no_voice_match: "No tienes permiso para acceder a la base de datos de contraseñas."
    it:
      unknown_entry: [ "Non ho trovato credenziali per {}." ]
      typed_pw: "Password digitata per {}"
      db_not_found: "Il database delle password non è stato trovato."
      key_not_found: "La chiave per accedere al database non è stata trovata."
      could_not_access_keystore: "Impossibile aprire il database delle password."
      no_voice_match: "Non sei autorizzato ad accedere al database delle password."
    ja:
      unknown_entry: [ "{} の資格情報が見つかりませんでした。" ]
      typed_pw: "{} のパスワードを入力しました"
      db_not_found: "パスワードデータベースが見つかりませんでした。"
      key_not_found: "データベースにアクセスするためのキーが見つかりませんでした。"
      could_not_access_keystore: "パスワードデータベースを開くことができませんでした。"
      no_voice_match: "パスワードデータベースにアクセスする権限がありません。"
    ru:
      unknown_entry: [ "Я не нашел учетные данные для {}." ]
      typed_pw: "Введен пароль для {}"
      db_not_found: "База данных паролей не найдена."
      key_not_found: "Ключ для доступа к базе данных не найден."
      could_not_access_keystore: "Не удалось открыть базу данных паролей."
      no_voice_match: "У вас нет доступа к базе данных паролей."

    db_file: ./pw.kdbx
    key_file: ./key.keyx
