intent:
  password:
    de:
      unknown_entry: [ "Ich habe keine Zugangsdaten für {} gefunden." ]
      typed_pw: "Passwort für {} getippt"
      db_not_found: "Die Passwortdatenbank wurde nicht gefunden."
      key_not_found: "Der Schlüssel für die Datenbank wurde nicht gefunden."
      could_not_access_keystore: "Konnte Passwortdatenbank nicht öffnen."
      no_voice_match: "Du darfst leider nicht auf die Passwortdatenbank zugreifen."
      no_session: "Die Sitzung existiert nicht . Bitte starten Sie den Vorgang erneut ."
      new_entity_title: "Was ist der Titel des neuen Datenbankeintrags?"
      new_entity_username: "Bitte gib den Benutzernamen für den Eintrag an."
      new_entity_pw: "Bitte gib das Passwort für den Eintrag an."
      no_speaker: "Ich konnte keinen Sprecher identifizieren."
      db_user_not_found: [ "Die Datenbank für Benutzer {} konnte nicht gefunden werden." ]
      new_entity_success: [ "Der Eintrag '{}' wurde erfolgreich hinzugefügt." ]
      new_entity_error: "Es gab einen Fehler beim Hinzufügen des Eintrags."
      check_up_title: "Der Titel lautet {}. Ist das korrekt? Antworte mit 'Ja' oder 'Nein'"
      check_up_username: "Der Benutzername lautet {}. Ist das korrekt? Antworte mit 'Ja' oder 'Nein'"
      check_up_pw: "Das Passwort lautet {}. Ist das korrekt? Antworte mit 'Ja' oder 'Nein'"
      retry_title: "Bitte gib den Titel erneut an."
      retry_username: "Bitte gib den Benutzernamen erneut an."
      retry_pw: "Bitte gib das Passwort erneut an."
      finish_entity: "Der Eintrag wurde erfolgreich abgeschlossen!"
      invalid_response: "Ungültige Eingabe. Bitte antworte mit 'Ja' oder 'Nein'."
      char_map: "eins=1,zwei=2,drei=3,vier=4,fünf=5,sechs=6,sieben=7,acht=8,neun=9,null=0,at=@,punkt=.,dot=.,minus=-,bindestrich=-,unterstrich=_,dollar=$,prozent=%,und=&,stern=*,hashtag=#,plus=+,fragezeichen=?,ausrufezeichen=!,slash=/,backslash=\\"

    en:
      unknown_entry: [ "I could not find any credentials for {}." ]
      typed_pw: "Typed password for {}"
      db_not_found: "The key database was not found."
      key_not_found: "The secret key to access the database was not found."
      could_not_access_keystore: "Could not open keystore"
      no_voice_match: "You are not allowed to access the keystore"
      no_session: "The session does not exist. Please restart the process."
      new_entity_title: "What is the title of the new database entry?"
      new_entity_username: "Please provide the username for the entry."
      new_entity_pw: "Please provide the password for the entry."
      no_speaker: "I could not identify a speaker."
      db_user_not_found: [ "The database for user {} could not be found." ]
      new_entity_success: [ "The entry '{}' has been successfully added." ]
      new_entity_error: "There was an error adding the entry."
      check_up_title: "The title is {}. Is this correct? Answer 'Yes' or 'No'."
      check_up_username: "The username is {}. Is this correct? Answer 'Yes' or 'No'."
      check_up_pw: "The password is {}. Is this correct? Answer 'Yes' or 'No'."
      retry_title: "Please provide the title again."
      retry_username: "Please provide the username again."
      retry_pw: "Please provide the password again."
      finish_entity: "The entry has been successfully completed!"
      invalid_response: "Invalid input. Please respond with 'Yes' or 'No'."
      char_map: "one=1,two=2,three=3,four=4,five=5,six=6,seven=7,eight=8,nine=9,zero=0,at=@,dot=.,point=.,minus=-,dash=-,underscore=_,dollar=$,percent=%,and=&,star=*,hash=#,plus=+,questionmark=?,exclamationmark=!,slash=/,backslash=\\"

    fr:
      unknown_entry: [ "Je n'ai trouvé aucune donnée d'accès pour {}." ]
      typed_pw: "Mot de passe tapé pour {}"
      db_not_found: "La base de données des mots de passe n'a pas été trouvée."
      key_not_found: "La clé secrète pour accéder à la base de données n'a pas été trouvée."
      could_not_access_keystore: "Impossible d'ouvrir la base de données des mots de passe."
      no_voice_match: "Vous n'êtes pas autorisé à accéder à la base de données des mots de passe."
      no_session: "La session n'existe pas. Veuillez redémarrer le processus."
      new_entity_title: "Quel est le titre de la nouvelle entrée dans la base de données ?"
      new_entity_username: "Veuillez fournir le nom d'utilisateur pour l'entrée."
      new_entity_pw: "Veuillez fournir le mot de passe pour l'entrée."
      no_speaker: "Je n'ai pas pu identifier un locuteur."
      db_user_not_found: [ "La base de données pour l'utilisateur {} est introuvable." ]
      new_entity_success: [ "L'entrée '{}' a été ajoutée avec succès." ]
      new_entity_error: "Une erreur est survenue lors de l'ajout de l'entrée."
      check_up_title: "Le titre est {}. Est-ce correct ? Répondez 'Oui' ou 'Non'."
      check_up_username: "Le nom d'utilisateur est {}. Est-ce correct ? Répondez 'Oui' ou 'Non'."
      check_up_pw: "Le mot de passe est {}. Est-ce correct ? Répondez 'Oui' ou 'Non'."
      retry_title: "Veuillez fournir à nouveau le titre."
      retry_username: "Veuillez fournir à nouveau le nom d'utilisateur."
      retry_pw: "Veuillez fournir à nouveau le mot de passe."
      finish_entity: "L'entrée a été complétée avec succès !"
      invalid_response: "Entrée invalide. Veuillez répondre par 'Oui' ou 'Non'."
      char_map: "un=1,deux=2,trois=3,quatre=4,cinq=5,six=6,sept=7,huit=8,neuf=9,zéro=0,arobase=@,point=.,dot=.,moins=-,tiret=-,souligné=_,dollar=$,pourcentage=%,et=&,étoile=*,dièse=#,plus=+,pointdinterrogation=?,pointdexclamation=!,slash=/,backslash=\\"

    es:
      unknown_entry: [ "No encontré ninguna credencial para {}." ]
      typed_pw: "Contraseña escrita para {}"
      db_not_found: "No se encontró la base de datos de contraseñas."
      key_not_found: "No se encontró la clave para acceder a la base de datos."
      could_not_access_keystore: "No se pudo abrir la base de datos de contraseñas."
      no_voice_match: "No tienes permiso para acceder a la base de datos de contraseñas."
      no_session: "La sesión no existe. Por favor, reinicie el proceso."
      new_entity_title: "¿Cuál es el título de la nueva entrada en la base de datos?"
      new_entity_username: "Por favor, proporcione el nombre de usuario para la entrada."
      new_entity_pw: "Por favor, proporcione la contraseña para la entrada."
      no_speaker: "No pude identificar un hablante."
      db_user_not_found: [ "No se pudo encontrar la base de datos para el usuario {}." ]
      new_entity_success: [ "La entrada '{}' se ha añadido con éxito." ]
      new_entity_error: "Hubo un error al añadir la entrada."
      check_up_title: "El título es {}. ¿Es correcto? Responda 'Sí' o 'No'."
      check_up_username: "El nombre de usuario es {}. ¿Es correcto? Responda 'Sí' o 'No'."
      check_up_pw: "La contraseña es {}. ¿Es correcto? Responda 'Sí' o 'No'."
      retry_title: "Por favor, proporcione el título de nuevo."
      retry_username: "Por favor, proporcione el nombre de usuario de nuevo."
      retry_pw: "Por favor, proporcione la contraseña de nuevo."
      finish_entity: "¡La entrada se ha completado con éxito!"
      invalid_response: "Entrada no válida. Por favor, responda con 'Sí' o 'No'."
      char_map: "uno=1,dos=2,tres=3,cuatro=4,cinco=5,seis=6,siete=7,ocho=8,nueve=9,cero=0,arroba=@,punto=.,dot=.,menos=-,guion=-,guionbajo=_,dolar=$,porciento=%,y=&,estrella=*,almohadilla=#,mas=+,interrogacion=?,exclamacion=!,slash=/,backslash=\\"

    it:
      unknown_entry: [ "Non ho trovato credenziali per {}." ]
      typed_pw: "Password digitata per {}"
      db_not_found: "Il database delle password non è stato trovato."
      key_not_found: "La chiave per accedere al database non è stata trovata."
      could_not_access_keystore: "Impossibile aprire il database delle password."
      no_voice_match: "Non sei autorizzato ad accedere al database delle password."
      no_session: "La sessione non esiste. Si prega di riavviare il processo."
      new_entity_title: "Qual è il titolo della nuova voce nel database?"
      new_entity_username: "Si prega di fornire il nome utente per la voce."
      new_entity_pw: "Si prega di fornire la password per la voce."
      no_speaker: "Non sono riuscito a identificare un parlante."
      db_user_not_found: [ "Il database per l'utente {} non è stato trovato." ]
      new_entity_success: [ "La voce '{}' è stata aggiunta con successo." ]
      new_entity_error: "Si è verificato un errore durante l'aggiunta della voce."
      check_up_title: "Il titolo è {}. È corretto? Rispondi 'Sì' o 'No'."
      check_up_username: "Il nome utente è {}. È corretto? Rispondi 'Sì' o 'No'."
      check_up_pw: "La password è {}. È corretto? Rispondi 'Sì' o 'No'."
      retry_title: "Si prega di fornire di nuovo il titolo."
      retry_username: "Si prega di fornire di nuovo il nome utente."
      retry_pw: "Si prega di fornire di nuovo la password."
      finish_entity: "La voce è stata completata con successo!"
      invalid_response: "Risposta non valida. Si prega di rispondere con 'Sì' o 'No'."
      char_map: "uno=1,due=2,tre=3,quattro=4,cinque=5,sei=6,sette=7,otto=8,nove=9,zero=0,chiocciola=@,punto=.,dot=.,meno=-,trattino=-,sottolineato=_,dollaro=$,percento=%,e=&,stella=*,cancelletto=#,più=+,domanda=?,esclamazione=!,slash=/,backslash=\\"

    ja:
      unknown_entry: [ "{} の資格情報が見つかりませんでした。" ]
      typed_pw: "{} のパスワードを入力しました"
      db_not_found: "パスワードデータベースが見つかりませんでした。"
      key_not_found: "データベースにアクセスするためのキーが見つかりませんでした。"
      could_not_access_keystore: "パスワードデータベースを開くことができませんでした。"
      no_voice_match: "パスワードデータベースにアクセスする権限がありません。"
      no_session: "セッションが存在しません。プロセスを再開してください。"
      new_entity_title: "新しいデータベースエントリのタイトルは何ですか？"
      new_entity_username: "エントリのユーザー名を入力してください。"
      new_entity_pw: "エントリのパスワードを入力してください。"
      no_speaker: "話者を特定できませんでした。"
      db_user_not_found: [ "ユーザー {} のデータベースが見つかりませんでした。" ]
      new_entity_success: [ "エントリ '{}' が正常に追加されました。" ]
      new_entity_error: "エントリの追加中にエラーが発生しました。"
      check_up_title: "タイトルは {} です。正しいですか？「はい」または「いいえ」で答えてください。"
      check_up_username: "ユーザー名は {} です。正しいですか？「はい」または「いいえ」で答えてください。"
      check_up_pw: "パスワードは {} です。正しいですか？「はい」または「いいえ」で答えてください。"
      retry_title: "タイトルをもう一度入力してください。"
      retry_username: "ユーザー名をもう一度入力してください。"
      retry_pw: "パスワードをもう一度入力してください。"
      finish_entity: "エントリが正常に完了しました！"
      invalid_response: "無効な入力です。「はい」または「いいえ」で回答してください。"
      char_map: "いち=1,に=2,さん=3,し=4,ご=5,ろく=6,なな=7,はち=8,きゅう=9,ぜろ=0,アットマーク=@,てん=.,ドット=.,マイナス=-,ハイフン=-,アンダーバー=_,ドル=$,パーセント=%,アンド=&,スター=*,ハッシュ=#,プラス=+,はてな=？,びっくり=！,スラッシュ=/,バックスラッシュ=\\"

    ru:
      unknown_entry: [ "Я не нашел учетные данные для {}." ]
      typed_pw: "Введен пароль для {}"
      db_not_found: "База данных паролей не найдена."
      key_not_found: "Ключ для доступа к базе данных не найден."
      could_not_access_keystore: "Не удалось открыть базу данных паролей."
      no_voice_match: "У вас нет доступа к базе данных паролей."
      no_session: "Сессия не существует. Пожалуйста, начните процесс заново."
      new_entity_title: "Каково название новой записи в базе данных?"
      new_entity_username: "Пожалуйста, введите имя пользователя для записи."
      new_entity_pw: "Пожалуйста, введите пароль для записи."
      no_speaker: "Не удалось идентифицировать говорящего."
      db_user_not_found: [ "База данных для пользователя {} не найдена." ]
      new_entity_success: [ "Запись '{}' успешно добавлена." ]
      new_entity_error: "Произошла ошибка при добавлении записи."
      check_up_title: "Название: {}. Это правильно? Ответьте 'Да' или 'Нет'."
      check_up_username: "Имя пользователя: {}. Это правильно? Ответьте 'Да' или 'Нет'."
      check_up_pw: "Пароль: {}. Это правильно? Ответьте 'Да' или 'Нет'."
      retry_title: "Пожалуйста, введите название еще раз."
      retry_username: "Пожалуйста, введите имя пользователя еще раз."
      retry_pw: "Пожалуйста, введите пароль еще раз."
      finish_entity: "Запись успешно завершена!"
      invalid_response: "Неверный ввод. Пожалуйста, ответьте 'Да' или 'Нет'."
      char_map: "один=1,два=2,три=3,четыре=4,пять=5,шесть=6,семь=7,восемь=8,девять=9,ноль=0,собака=@,точка=.,дот=.,минус=-,тире=-,нижнее_подчеркивание=_,доллар=$,процент=%,и=&,звезда=*,решетка=#,плюс=+,вопрос=?,восклицание=!,слэш=/,обратныйслэш=\\"
